/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AgeSlugRouteImport } from './routes/age.$slug'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeSlugRoute = AgeSlugRouteImport.update({
  id: '/age/$slug',
  path: '/age/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/offers': typeof OffersRoute
  '/shop': typeof ShopRoute
  '/age/$slug': typeof AgeSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/offers': typeof OffersRoute
  '/shop': typeof ShopRoute
  '/age/$slug': typeof AgeSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/offers': typeof OffersRoute
  '/shop': typeof ShopRoute
  '/age/$slug': typeof AgeSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brands'
    | '/categories'
    | '/contact'
    | '/offers'
    | '/shop'
    | '/age/$slug'
    | '/blog/$slug'
    | '/category/$slug'
    | '/product/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brands'
    | '/categories'
    | '/contact'
    | '/offers'
    | '/shop'
    | '/age/$slug'
    | '/blog/$slug'
    | '/category/$slug'
    | '/product/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brands'
    | '/categories'
    | '/contact'
    | '/offers'
    | '/shop'
    | '/age/$slug'
    | '/blog/$slug'
    | '/category/$slug'
    | '/product/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandsRoute: typeof BrandsRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  OffersRoute: typeof OffersRoute
  ShopRoute: typeof ShopRoute
  AgeSlugRoute: typeof AgeSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age/$slug': {
      id: '/age/$slug'
      path: '/age/$slug'
      fullPath: '/age/$slug'
      preLoaderRoute: typeof AgeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandsRoute: BrandsRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  OffersRoute: OffersRoute,
  ShopRoute: ShopRoute,
  AgeSlugRoute: AgeSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
